name: Email Cron Job

on:
  schedule:
    - cron: "*/12 * * * *"  # every 12 minutes
  workflow_dispatch:        # allows manual trigger

jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"  # 🔧 this is the fix

      - name: Install dependencies
        run: pip install requests

      - name: Run Python script
        run: python check_email.py
